### ISSUE TITLE
Readme issues and singles possibilities

### ISSUE THREAD

**Issue by Danfun64** [gravitypriest/dragon-radar#1]
I thought that the R1 Funi Dragon Box subs and audio could be transferred to the R2 Toei Dragon Boxes, but for whatever reason the R1 DBoxZ sets aren't mentioned.

Of less importance, you mentioned the *very rare* possibility of using the Saban singles (no reference to the Rock the Dragon sets for whatever reason...) but not the BLT dub of DB 1-13 (I don't think it requires as much editing as the Saban dub...)

And then of course comes the possibility of syncing the pioneer dubs (either through uncut laserdisc, uncut dvd, or rock the dragon (movie 1 and 2 only) ) and the PAL sources listed at http://www.kanzenshuu.com/forum/viewtopic.php?f=7&t=33653&start=20#p1088885

**Comment by gravitypriest** [comment]
I wrote up the readme changes pretty late last night -- but yeah, I forgot to mention the Funi DBox Z.  I DO have framedata for it, but unfortunately I don't have those sets anymore, so I am unable to determine the demux info for those discs.  I'll have to get that metadata from someone who does own those discs -- will investigate this later on and figure a method to easily show someone how to obtain that data.

**Comment by gravitypriest** [comment]
Closed for now as there are no current plans to edit/encode video in the scope of this project.
