### ISSUE TITLE
Support for just adding subs to a 1:1 DVD copy.

### ISSUE THREAD

**Issue by Damned496** [gravitypriest/dragon-radar#2]
Hey man,

I was wondering if you could possibly add support for just adding R1 Dragon Box subs to R2 Dragon Box Z Volume 2 DVDs. No encoding to MKVs, no touching the video, audio, or menus in any way. Only adding the subs to the DVDs.

Alternatively, if you don't feel up to adding this feature, a detailed guide up on Kanzenshuu on how to handle the unique cell structure of those DVDs would suffice

**Comment by Danfun64** [comment]
...why only "Volume 2"? Also, what about direct copy from other sources?

**Comment by Damned496** [comment]
_why only "Volume 2"?_

I already have subtitles on every other Dragon Box. I only need them for Volume 2 of Dragon Box Z. Adding 1:1 sub support for all the other R2 Dragon Boxes would be awesome as well.

_Also, what about direct copy from other sources?_

The more the merrier. All I would use is an R1 Dragon Box sub to 1:1 Dragon Box Z Volume 2 option though.

**Comment by Danfun64** [comment]
I still hope that one day @gravitypriest will support the DBGT singles because of their containing subs for the NEPS.

**Comment by gravitypriest** [comment]
@Damned496 Adding subs in that way is doable, but it's a much more complicated process that cannot be completely automated with simple scripting.  Even though you're "not touching the menus, video, audio," with the way DVDs work, you need to completely unravel the audio & video streams, then put them back together with the subs.  On top of that, re-inserting them into the original DVD is a good bit of work itself.  I wouldn't mind putting a guide together for it, but it's a very tedious process.  I have tried to automate it before and it's much more complex and difficult than simply throwing an MKV together.

@Danfun64 I can support them, but I don't have those discs and cannot collect structure info from them.  Maybe sometime in the future, or perhaps someone who does have the discs can contribute the data.  I can put a guide together on how to do it eventually.

**Comment by Damned496** [comment]
Understood. If you are not feeling up to it, I'm familiar enough with how the re-author process works, I just need to figure out how to handle the unique cell structure of the DVDs when remuxing / reauthoring.

**Comment by gravitypriest** [comment]
Closing because this isn't within the scope of the project, however,  I will consider making a guide available.
