### ISSUE TITLE
Ability to set the working directory.

### ISSUE THREAD

**Issue by LaunchSneezed** [gravitypriest/dragon-radar#6]
Maybe an INI option to set the working directory if one doesn't want to use the Windows temp folder.

We can simply change the Windows temp folder setting, I know. But it feels nicer to just tell DR which folder to use for temp files and have it use that directory for everything.

**Comment by gravitypriest** [comment]
Good thinking-- these are large files to work with and it'd be handy to set the desired dir locally instead of changing env variables.

**Comment by gravitypriest** [comment]
Fixed in 1.1.0
